# Generated by Django 5.2 on 2025-04-23 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_parcel_declared_value_usd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='delivery_price_usd',
            new_name='delivery_price',
        ),
    ]
