# Generated by Django 5.2 on 2025-04-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0003_rename_delivery_price_usd_parcel_delivery_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
