# Generated by Django 5.2 on 2025-04-28 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0004_alter_parcel_weight_kg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcel',
            options={'ordering': ['id']},
        ),
    ]
